### ISSUE TITLE
maximumEntries after excludedEvents

### ISSUE THREAD

**Issue by Dasty87** [jclarke0000/MMM-MyCalendar#6]
If i set maximumEntries to 20 my Calendar shows me only 4 Entries because of excludedEvents

**Comment by jclarke0000** [comment]
This should be fixed now in v2.0.  I updated the node_helper.js and calendarfetcher.js from the default calendar module, which I believe also perviously had this problem and was subsequently fixed.  Give it a shot and let me know if it is fixed now.  Also, with version 2.0, I'm now using the Nunjucks templating engine for the DOM layout.  As such you will need to use MagicMirror v2.2.0 or higher to get this fix.  Otherwise, you can simply copy over node_help.js and calendarfetcher.js from the default calendar module into your MMM-MyCalendar directory, and that *should* resolve it.

**Comment by drippyer** [comment]
I seem to be encountering this issue again currently. Looking into potential causes
